@include('website.layout.header')
@yield('head-links')
@include('website.layout.headerbar')
@yield('main-body')
@include('website.layout.footerbar')
@include('website.layout.footer')
@yield('footer-links')
